language: node_js
node_js:
- '0.10'
- '0.12'
env:
  global:
  - secure: S4k6MtsTeuynthiRmpOVSBs9aVs6Fo1Bav6136a5IPprDMnH3aXGMqNtXe8gL2k6Ddt/UIVE+Ib/kk9mlBHvEKeQPyK7v4M4LAI5jaBENaySQJq/OI3hikDFxw2zByaxjAAHZ6quJkZBVA0odKwRonV7d7xnYZJ3gl7SLK4n6lw=
install:
- npm install
cache:
  directories:
  - node_modules
script:
- npm run-script jshint
- npm test
- npm run-script coveralls
- npm run-script test-dist
deploy:
  provider: npm
  api_key:
    secure: iX4IdMDpceD95iXwmboCh94uDam3R3LtYga9zMqtZYcFq+0pCpBxr2AIF2xLltK1i2iOh01Du0Jmkjc1M/j1S1/ZlzqtLXHjrMPAXjjblzkAAZFVyrwfczAh3e5apo6O1ytEUTydyphhvBHMJKv4BkVMd747PZYQNKrhDgy1i6Y=
  email:
    secure: T9JxttaJM1tE/3GzprP3s3jKdb1j2DZZBqNYAqvIBhLbnr+jofmuA8yoIEyNvLH/M4/lyWp8msTm6X5M7FClI+9FM3Wu6l20yXWzG35ExZuQzMpq3+uXkvPOrlw2JmptQ0bFhCsOiKP2Ayyh0c5k4Dazr+DF4ILn1M71n3S/xgk=
  provider: npm
  on:
    branch: master
    tags: true
    node: '0.12'
